version: "3"
services:
  {% for i in range(N_GPU) %}
  ubuntu{{i}}:
    image: ubuntu:latest
    container_name: tail{{i}}
    command: tail -f /var/log/sysloog
  {% endfor %}
  ubuntulog:
    image: ubuntu:latest
    container_name: taillog
    command: tail -f /var/log/sysloog
    {% if rsyslog == 'true' %}
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://graylog.fyl.quzed.com:1516"
        tag: ${HOSTNAME}-bind9
    {% endif %}
    
